### ISSUE TITLE
Enemy without end points - NullReferenceException

### ISSUE THREAD

**Issue by AlesZurek** [Smehi/WaveOne#1]
Hi,
first I have to say that this is cool project.
I found some little issue.

I am getting error NullReferenceException: Object reference not set to an instance of an object
I was debugging and I found that you are trying to get Count on null when I have enemy which doesn't have navMesh (enemy which is in EndPoint.noEndPointEnemies)

https://github.com/Smehi/WaveOne/blob/9dfc5e2ea97841a5dbe026314776342a75b3410b/Assets/Wave%20One/Assets/Scripts/Spawners/PerWaveCustom.cs#L184

`endPoints.GetEndPoints` returns null in my case

**Comment by Smehi** [comment]
Hi, I know this is very late but I still want to say thank you for trying out the asset and putting in an issue on the GitHub page. I have just pushed an update (to the repo not the asset on the asset store, which I will do soon) that should fix this very issue and also another regarding excluding a certain agent from end points.

I hope you could fix this issue yourself back when you used the asset and had some fun with the asset :)
