### ISSUE TITLE
Null Object Reference error using non navmesh 2d enemies

### ISSUE THREAD

**Issue by ScbySnak** [Smehi/WaveOne#2]
NullReferenceException: Object reference not set to an instance of an object
SemihOrhan.WaveOne.Spawners.PerWaveCustom+<DeployTroops>d__46.MoveNext () (at Assets/Plugins/Wave One/Assets/Scripts/Spawners/PerWaveCustom.cs:144)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e98ed0368295432e8c11e52d6243ee11>:0)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
SemihOrhan.WaveOne.Spawners.PerWaveCustom:StartWave() (at Assets/Plugins/Wave One/Assets/Scripts/Spawners/PerWaveCustom.cs:102)

**Comment by Smehi** [comment]
Hi, I know this is very late however, I have not tested the asset with 2D objects and non Unity Navmesh is also not supported currently :( I can't tell which of the two is the culprit for the error but I think it is either of those (assuming everything is set up correctly).
